version: "3"
networks:
  php_network:

services:
  nginx_service:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
      - ./api/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_service
    networks:
      - php_network

  php_service:
    build: ./api
    container_name: desafio-php-fb
    working_dir: /var/www/html
    networks:
      - php_network
    volumes:
      - ./api:/var/www/html
      - ./api/xdebug/docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  
  node_fb:
    build: ./web
    container_name: desafio-node-fb
    command: npm run serve
    depends_on:
      - nginx_service
    working_dir: '/web'
    ports:
      - "8089:8080"