---
openapi: 3.0.0
info:
  title: API php-challenge-20201117
  description: Teste Codesh
  version: v1
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/filipborgs/php-challenge-20201117/v1
- url: http://localhost:8000/api/v1
paths:
  /:
    get:
      summary: Return the challenge message
      responses:
        "200":
          description: Message
          
  /products:
    get:
      summary: Return all products
      security: 
      - api_key: []
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductFullId'
    post:
      summary: Update a product
      security: 
      - api_key: []
      requestBody:
         content:
          multipart/form-data:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    $ref: '#/components/schemas/Product'
                  format: application/json
      responses:
        "200":
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
        "400":
          description: Missing id in path
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
  
  /products/paginate:
    get:
      summary: Return all products paginated
      security: 
      - api_key: []
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page: 
                    type: integer
                  first_page_url:
                    type: string
                  from:
                    type: integer
                  last_page:
                    type: integer
                  last_page_url:
                    type: string
                  next_page_url:
                    type: string
                  path:
                    type: string
                  per_page:
                    type: integer
                  prev_page_url:
                    type: string
                  to:
                    type: integer
                  total:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductBasic'

  /products/{idProduct}:
    put:
      summary: Update a product
      security: 
      - api_key: []
      parameters: 
        - name: 'idProduct'
          in: path
          description: The product id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product: 
                  $ref: '#/components/schemas/Product'
        description: Updated product object
        required: true
      responses:
        "200":
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
        "400":
          description: Missing id in path
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
    
    get:
      summary: Return a single product
      security: 
      - api_key: []
      parameters: 
        - name: 'idProduct'
          in: path
          description: The product id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductFullId'
        "400":
          description: Invalid object in request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'

    delete:
      summary: Delete a product
      security: 
      - api_key: []
      parameters: 
        - name: 'idProduct'
          in: path
          description: The product id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Product deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
        "400":
          description: Invalid object in request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
        "409":
          description: Unable to delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageJson'
components:
  schemas:
    MessageJson:
      type: object
      properties:
        message: 
          type: string
    ProductBasic:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        price:
          type: number
        rating:
          type: integer
        created_at:
          type: string
      description: Product object
      
    ProductFullId:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        filename:
          type: string
        width:
          type: integer
        height:
          type: integer
        price:
          type: number
        rating:
          type: integer
        created_at:
          type: string
      description: Product object
      
    Product:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        type:
          type: string
        filename:
          type: string
        width:
          type: integer
        height:
          type: integer
        price:
          type: number
        rating:
          type: integer
      description: Product object
    
  securitySchemes:
    api_key:
      type: apiKey
      name: key
      in: header